version: '3.8'

services:
  nextjs:
    build:
      dockerfile: ./apps/frontend/Dockerfile
      context: ./apps/frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - redis
  nestjs:
    build:
      dockerfile: ./apps/backend/Dockerfile
      context: ./apps/backend
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"